#!/bin/sh

pushd apps
jmake Makefiles
rm Makefile*
cd SieveOfEratosthenes
rm Makefile*
popd
pushd nodelibraries
jmake Makefiles
rm Makefile*
popd
pushd test
jmake Makefiles
rm Makefile*
popd
pushd tools
jmake Makefiles
rm Makefile*
popd
hg add "re:.*/Makefile\..*"
