#!/bin/sh

port=`echo 1024+$RANDOM | bc`
../../../apps/RemoteDatabase/RemoteDatabase localhost $port &
./distributed --name=kernel_3 --db-host=localhost --db-port=$port -cno&
./distributed --name=kernel_2 --db-host=localhost --db-port=$port -cno&
./distributed --name=kernel_1 --db-host=localhost --db-port=$port -cno&
./distributed --name=kernel_0 --db-host=localhost --db-port=$port
wait
