#!/bin/sh

port=`echo 1024+$RANDOM | bc`
../../../apps/RemoteContext/RemoteContext localhost $port &
./distributed --name=kernel_3 --ctx-host=localhost --ctx-port=$port -cno&
./distributed --name=kernel_2 --ctx-host=localhost --ctx-port=$port -cno&
./distributed --name=kernel_1 --ctx-host=localhost --ctx-port=$port -cno&
./distributed --name=kernel_0 --ctx-host=localhost --ctx-port=$port
wait
